name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: buckaroobanzay/mtt@main
      with:
        modname: digibuilder
        git_dependencies: |
          https://github.com/minetest-mods/digilines
          https://github.com/minetest-mirrors/farming
          https://github.com/OgelGames/fakelib
